### ISSUE TITLE
How to send sms using trial account?

### ISSUE THREAD

**Issue by zahidaziz** [aloha/laravel4-twilio#24] opened 2015-01-12 06:24 UTC
I am using aloha twilio to send sms. I already follow exactly the trial account terms to send sms.. But I still unable to send. This is the latest exception occurs from the package used.  

Error: SSL certificate problem: self signed certificate in certificate chain

Please help me...

**Comment by hannesvdvreken** [comment] 2015-01-17 08:44
Duplicate of #23

**Closed** 2015-01-17 16:48 UTC
